# Generated by Django 5.0.6 on 2024-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0003_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="list.tag"
            ),
        ),
    ]
